sdk: /Users/macboypro/src/rhodes 
sdkversion: 1.5
name: droid
version: 1.0
vendor: rhomobile
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator3.0
  provisionprofile:
  codesignidentity:
  entitlements:
extensions: ["extension-name-here", "second-extension-name"]
