sdk: "/Library/Ruby/Gems/1.8/gems/rhodes-1.4.1"
sdkversion: 1.4.1
name: droid
version: 1.0
vendor: rhomobile
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator3.0
  provisionprofile:
  codesignidentity:
  entitlements:
extensions: ["extension-name-here", "second-extension-name"]
